name: Windows Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./
        shell: powershell

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Building with Python script
        run: python build.py

      - name: Check 'SpaceEngine' library build success
        run: |
          if (Test-Path build\core\libSpaceEngine.a) {
            Write-Output "SpaceEngine library exists."
          } else {
            Write-Output "SpaceEngine library not found. Failing the CI test."
            exit 1
          }

      - name: Check 'SpaceEditor' executable build success
        run: |
          if (Test-Path build\editor\Space.exe) {
            Write-Output "SpaceEditor executable exists."
          } else {
            Write-Output "SpaceEditor executable not found. Failing the CI test."
            exit 1
          }

      - name: Check 'SpaceTests' executable build success
        run: |
          if (Test-Path build\tests\SpaceTests.exe) {
            Write-Output "SpaceTests executable exists."
          } else {
            Write-Output "SpaceTests executable not found. Failing the CI test."
            exit 1
          }

      - name: Run tests
        run: |
          cd build\tests
          .\SpaceTests > test_output.txt 2>&1

      - name: Check test results
        run: |
          if (Select-String -Path build\tests\test_output.txt -Pattern "failed") {
            Write-Output "Tests failed."
            exit 1
          } else {
            Write-Output "Tests passed."
          }